import { createContext, useContext, useEffect, useMemo, useState } from "react";

// Hand-picked demo customers spanning every segment x risk-profile combination,
// out of the 5,000 synthetic profiles generated by the backend. Lets a judge/demo
// audience switch personas instantly without needing a login flow.
export const DEMO_CUSTOMERS = [
  { id: "IDBI000001", name: "Advik Maharaj", segment: "Affluent", risk: "Conservative", city: "Mumbai" },
  { id: "IDBI000002", name: "Isaac Dewan", segment: "Mass", risk: "Aggressive", city: "Dehradun" },
  { id: "IDBI000003", name: "Caleb Sami", segment: "Affluent", risk: "Moderate", city: "Guwahati" },
  { id: "IDBI000006", name: "Ira Saini", segment: "Mass", risk: "Moderate", city: "Coimbatore" },
  { id: "IDBI000011", name: "Ranveer Chatterjee", segment: "Affluent", risk: "Aggressive", city: "Nashik" },
  { id: "IDBI000012", name: "Pooja Lalla", segment: "HNI", risk: "Aggressive", city: "Raipur" },
  { id: "IDBI000013", name: "Victor Yadav", segment: "Mass", risk: "Conservative", city: "Chennai" },
  { id: "IDBI000015", name: "Radhika Handa", segment: "HNI", risk: "Moderate", city: "Coimbatore" },
  { id: "IDBI000017", name: "Balveer Kaul", segment: "HNI", risk: "Conservative", city: "Nashik" },
];

export const LANGUAGES = ["English", "Hindi", "Tamil", "Telugu", "Bengali", "Marathi"];

const CustomerContext = createContext(null);

export function CustomerProvider({ children }) {
  const [customerId, setCustomerId] = useState(
    () => localStorage.getItem("dhanvi_customer_id") || DEMO_CUSTOMERS[0].id
  );
  const [language, setLanguage] = useState(
    () => localStorage.getItem("dhanvi_language") || "English"
  );

  useEffect(() => {
    localStorage.setItem("dhanvi_customer_id", customerId);
  }, [customerId]);

  useEffect(() => {
    localStorage.setItem("dhanvi_language", language);
  }, [language]);

  const currentDemo = useMemo(
    () => DEMO_CUSTOMERS.find((c) => c.id === customerId) || DEMO_CUSTOMERS[0],
    [customerId]
  );

  const value = { customerId, setCustomerId, language, setLanguage, currentDemo };

  return <CustomerContext.Provider value={value}>{children}</CustomerContext.Provider>;
}

export function useCustomer() {
  const ctx = useContext(CustomerContext);
  if (!ctx) throw new Error("useCustomer must be used within CustomerProvider");
  return ctx;
}
