import { useMemo } from "react";
import { LineChart, Line, ResponsiveContainer } from "recharts";
import PageHeader from "../components/PageHeader";
import { formatINR } from "../components/AnimatedNumber";
import { LoadingBlock, ErrorBlock } from "../components/StateViews";
import { useCustomer } from "../context/CustomerContext";
import { api } from "../api/client";
import useFetch from "../hooks/useFetch";
import "./Market.css";

function IndexCard({ name, index }) {
  const up = index.change_pct >= 0;
  const sparkData = index.sparkline.map((v, i) => ({ i, v }));
  return (
    <div className="card index-card">
      <div className="index-card-top">
        <span className="index-name">{name}</span>
        <span className={`index-change ${up ? "text-green" : "text-red"}`}>
          {up ? "▲" : "▼"} {Math.abs(index.change_pct)}%
        </span>
      </div>
      <div className="index-value">{index.value.toLocaleString("en-IN")}</div>
      <div className="index-spark">
        <ResponsiveContainer width="100%" height={44}>
          <LineChart data={sparkData}>
            <Line type="monotone" dataKey="v" stroke={up ? "#22c55e" : "#ef4444"} strokeWidth={2} dot={false} />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

export default function Market() {
  const { customerId, language } = useCustomer();
  const { data, loading, error } = useFetch(() => api.marketPulse(customerId, language), [customerId, language]);

  const insights = useMemo(() => {
    if (!data) return [];
    const list = [];
    const niftyUp = data.nifty.change_pct >= 0;
    list.push({
      icon: niftyUp ? "📈" : "📉",
      text: `Nifty is ${niftyUp ? "up" : "down"} ${Math.abs(data.nifty.change_pct)}% today, ${
        niftyUp ? "extending gains" : "under mild pressure"
      } across large-caps.`,
    });
    const goldUp = data.gold_change_pct >= 0;
    list.push({
      icon: "🥇",
      text: `Gold moved ${goldUp ? "up" : "down"} ${Math.abs(data.gold_change_pct)}% — ${
        goldUp ? "a good day for your SGB/digital gold holdings" : "a minor dip, unlikely to matter for a long-term gold allocation"
      }.`,
    });
    if (data.portfolio_impact) {
      const impactUp = data.portfolio_impact.estimated_portfolio_change >= 0;
      list.push({
        icon: impactUp ? "💰" : "🛡️",
        text: `Your equity + gold exposure (~₹${formatINR(
          data.portfolio_impact.equity_exposure_considered + data.portfolio_impact.gold_exposure_considered,
          { compact: true }
        )}) means today's move ${impactUp ? "added to" : "trimmed"} your portfolio value.`,
      });
    }
    list.push({
      icon: "🧭",
      text: "Historically, staying invested through short-term swings has outperformed trying to time entries and exits.",
    });
    return list;
  }, [data]);

  if (loading) {
    return (
      <>
        <PageHeader title="Market Pulse" subtitle="Today's markets, explained simply" />
        <LoadingBlock height={140} />
      </>
    );
  }
  if (error) {
    return (
      <>
        <PageHeader title="Market Pulse" subtitle="Today's markets, explained simply" />
        <ErrorBlock message={error.message} />
      </>
    );
  }

  return (
    <>
      <PageHeader title="Market Pulse" subtitle={new Date(data.date).toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long" })} />

      <div className="grid-2" style={{ marginTop: 10 }}>
        <IndexCard name="SENSEX" index={data.sensex} />
        <IndexCard name="NIFTY 50" index={data.nifty} />
      </div>

      <div className="section-title">Dhanvi's Market Take</div>
      <div className="card commentary-card">
        <p className="commentary-text">{data.commentary}</p>
        <span className={`badge ${data.commentary_ai_powered ? "badge-purple" : "badge-yellow"}`}>
          {data.commentary_ai_powered ? "AI-generated by Dhanvi" : "Rule-based (Gemini offline)"}
        </span>
      </div>

      {data.portfolio_impact && (
        <>
          <div className="section-title">Your Portfolio Impact</div>
          <div className="card impact-card">
            <div className="impact-label">Estimated change today</div>
            <div
              className={`impact-value ${data.portfolio_impact.estimated_portfolio_change >= 0 ? "text-green" : "text-red"}`}
            >
              {data.portfolio_impact.estimated_portfolio_change >= 0 ? "+" : ""}₹
              {formatINR(data.portfolio_impact.estimated_portfolio_change, { compact: true })}
            </div>
            <div className="impact-sub">
              Based on ~₹{formatINR(data.portfolio_impact.equity_exposure_considered, { compact: true })} equity + ₹
              {formatINR(data.portfolio_impact.gold_exposure_considered, { compact: true })} gold exposure
            </div>
          </div>
        </>
      )}

      <div className="section-title">Trending Insights</div>
      <div className="insight-list">
        {insights.map((ins, i) => (
          <div className="card insight-card" key={i}>
            <span className="insight-icon">{ins.icon}</span>
            <span className="insight-text">{ins.text}</span>
          </div>
        ))}
      </div>
    </>
  );
}
